FROM maven:3.9.6-amazoncorretto-21 AS jar

WORKDIR /opt/cosmic
COPY pom.xml ./pom.xml
COPY src ./src
RUN mvn -f ./pom.xml clean package -Dmaven.test.skip -T 1C

FROM amazoncorretto:21
WORKDIR /opt/server
COPY wz ./wz
COPY --from=jar /opt/cosmic/target/*.jar ./app.jar
COPY scripts ./scripts/
COPY config.yaml ./
EXPOSE 8484 7575 7576 7577
ENTRYPOINT ["java", "-jar", "./app.jar"]


