CREATE TABLE characters
(
    id                   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    accountid            INT          NOT NULL DEFAULT '0',
    world                INT          NOT NULL DEFAULT '0',
    name                 VARCHAR(13)  NOT NULL DEFAULT '',
    level                INT          NOT NULL DEFAULT '1',
    exp                  INT          NOT NULL DEFAULT '0',
    gachaexp             INT          NOT NULL DEFAULT '0',
    str                  INT          NOT NULL DEFAULT '12',
    dex                  INT          NOT NULL DEFAULT '5',
    luk                  INT          NOT NULL DEFAULT '4',
    int                  INT          NOT NULL DEFAULT '4',
    hp                   INT          NOT NULL DEFAULT '50',
    mp                   INT          NOT NULL DEFAULT '5',
    maxhp                INT          NOT NULL DEFAULT '50',
    maxmp                INT          NOT NULL DEFAULT '5',
    meso                 INT          NOT NULL DEFAULT '0',
    hpMpUsed             INT          NOT NULL DEFAULT '0',
    job                  INT          NOT NULL DEFAULT '0',
    skincolor            INT          NOT NULL DEFAULT '0',
    gender               INT          NOT NULL DEFAULT '0',
    fame                 INT          NOT NULL DEFAULT '0',
    fquest               INT          NOT NULL DEFAULT '0',
    hair                 INT          NOT NULL DEFAULT '0',
    face                 INT          NOT NULL DEFAULT '0',
    ap                   INT          NOT NULL DEFAULT '0',
    sp                   VARCHAR(128) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0',
    map                  INT          NOT NULL DEFAULT '0',
    spawnpoint           INT          NOT NULL DEFAULT '0',
    gm                   INT          NOT NULL DEFAULT '0',
    party                INT          NOT NULL DEFAULT '0',
    buddyCapacity        INT          NOT NULL DEFAULT '25',
    createdate           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rank                 INT          NOT NULL DEFAULT '1',
    rankMove             INT          NOT NULL DEFAULT '0',
    jobRank              INT          NOT NULL DEFAULT '1',
    jobRankMove          INT          NOT NULL DEFAULT '0',
    guildid              INT          NOT NULL DEFAULT '0',
    guildrank            INT          NOT NULL DEFAULT '5',
    messengerid          INT          NOT NULL DEFAULT '0',
    messengerposition    INT          NOT NULL DEFAULT '4',
    mountlevel           INT          NOT NULL DEFAULT '1',
    mountexp             INT          NOT NULL DEFAULT '0',
    mounttiredness       INT          NOT NULL DEFAULT '0',
    omokwins             INT          NOT NULL DEFAULT '0',
    omoklosses           INT          NOT NULL DEFAULT '0',
    omokties             INT          NOT NULL DEFAULT '0',
    matchcardwins        INT          NOT NULL DEFAULT '0',
    matchcardlosses      INT          NOT NULL DEFAULT '0',
    matchcardties        INT          NOT NULL DEFAULT '0',
    MerchantMesos        INT                   DEFAULT '0',
    HasMerchant          INT                   DEFAULT '0',
    equipslots           INT          NOT NULL DEFAULT '24',
    useslots             INT          NOT NULL DEFAULT '24',
    setupslots           INT          NOT NULL DEFAULT '24',
    etcslots             INT          NOT NULL DEFAULT '24',
    familyId             INT          NOT NULL DEFAULT '-1',
    monsterbookcover     INT          NOT NULL DEFAULT '0',
    allianceRank         INT          NOT NULL DEFAULT '5',
    vanquisherStage      INT          NOT NULL DEFAULT '0',
    ariantPoints         INT          NOT NULL DEFAULT '0',
    dojoPoints           INT          NOT NULL DEFAULT '0',
    lastDojoStage        INT          NOT NULL DEFAULT '0',
    finishedDojoTutorial INT          NOT NULL DEFAULT '0',
    vanquisherKills      INT          NOT NULL DEFAULT '0',
    summonValue          INT          NOT NULL DEFAULT '0',
    partnerId            INT          NOT NULL DEFAULT '0',
    marriageItemId       INT          NOT NULL DEFAULT '0',
    reborns              INT          NOT NULL DEFAULT '0',
    PQPoints             INT          NOT NULL DEFAULT '0',
    dataString           VARCHAR(64)  NOT NULL DEFAULT '',
    lastLogoutTime       TIMESTAMP    NOT NULL DEFAULT '2015-01-01 05:00:00',
    lastExpGainTime      TIMESTAMP    NOT NULL DEFAULT '2015-01-01 05:00:00',
    partySearch          INT          NOT NULL DEFAULT '1',
    jailexpire           BIGINT       NOT NULL DEFAULT '0'
);

CREATE INDEX characters_accountid_index ON characters (accountid);
CREATE INDEX characters_party_index ON characters (party);
CREATE INDEX characters_ranking1_index ON characters (level, exp);
CREATE INDEX characters_ranking2_index ON characters (gm, job);
CREATE INDEX characters_world_index ON characters (id, accountid, world);
CREATE INDEX characters_name_index ON characters (id, accountid, name);