CREATE TYPE BOSSTYPE AS ENUM ('ZAKUM','HORNTAIL','PINKBEAN','SCARGA','PAPULATUS');

CREATE TABLE bosslog_daily
(
    id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    characterid INT       NOT NULL,
    bosstype    BOSSTYPE NOT NULL,
    attempttime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bosslog_weekly
(
    id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    characterid INT       NOT NULL,
    bosstype    BOSSTYPE NOT NULL,
    attempttime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);